spring:
  application:
    name: mod-password-validator
#  datasource:
#    password: folio_admin
#    url: jdbc:postgresql://localhost:5432/okapi_modules
#    username: folio_admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: NON_EMPTY
feign:
  client:
    config:
      pwned-passwords:
        logger-level: full
folio:
  tenant:
    validation:
      enabled: true
pwned-passwords:
  client:
    url: https://api.pwnedpasswords.com
  padding:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace,liquibase
      base-path: /admin
server:
  port: 8081

