spring:
  application:
    name: mod-password-validator
  datasource:
    password: ${DB_PASSWORD:pass}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db}
    username: ${DB_USERNAME:user}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: NON_EMPTY
  cloud:
    openfeign:
      okhttp:
        enabled: true
  sql:
    init:
      continue-on-error: true
feign:
  client:
    config:
      pwned-passwords:
        logger-level: full
folio:
  tenant:
    validation:
      enabled: true
  logging:
    request:
      enabled: true
    feign:
      enabled: true
pwned-passwords:
  client:
    url: https://api.pwnedpasswords.com
  padding:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace,liquibase,loggers
      base-path: /admin
  endpoint:
    loggers:
      enabled: true
#  endpoint:
#    health:
#      show-details: always
#      show-components: always
###################################################
# Disable all checks except for readiness
###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
server:
  port: 8081
cache:
  eviction:
    time:
      validation-rule: 1800000